replicas: 2

image: "confluentinc/cp-kafka"
imageTag: "5.0.1"  # Confluent image for Kafka 2.0.0
imagePullPolicy: "IfNotPresent"

kafkaHeapOptions: "-Xmx1G -Xms1G"
updateStrategy:
  type: "OnDelete"

podManagementPolicy: OrderedReady

logSubPath: "logs"

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

terminationGracePeriodSeconds: 60

headless:
  port: 9092

external:
  enabled: true
  type: LoadBalancer
  dns:
    useInternal: true
    useExternal: true
  distinct: true
  servicePort: 19092
  firstListenerPort: 31090
  domain: servicex.ssl-hep.org
  loadBalancerIP: []
  init:
    image: "lwolf/kubectl_deployer"
    imageTag: "0.4"
    imagePullPolicy: "IfNotPresent"

configurationOverrides:
  "confluent.support.metrics.enable": false  # Disables confluent metric submission
  "advertised.listeners": |-
    EXTERNAL://kafka$((${KAFKA_BROKER_ID})).servicex.ssl-hep.org:19092
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

persistence:
  enabled: true
  size: "100Gi"
  mountPath: "/opt/kafka/data"
  storageClass: local-volumes

jmx:
  configMap:
    enabled: true
  port: 5555
  whitelistObjectNames:  # []
  - kafka.controller:*
  - kafka.server:*
  - java.lang:*
  - kafka.network:*
  - kafka.log:*

prometheus:
  jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: a23062396cd5af1acdf76512632c20ea6be76885dfc20cd9ff40fb23846557e8
    interval: 10s
    scrapeTimeout: 10s
    port: 5556
  kafka:
    enabled: true
    image: danielqsj/kafka-exporter
    imageTag: v1.2.0
    interval: 10s
    scrapeTimeout: 10s
    port: 9308
  operator:
    enabled: true
    serviceMonitor:
      namespace: kafka
      selector:
        prometheus: kube-prometheus

configJob:
  backoffLimit: 6

zookeeper:
  enabled: true
  resources: ~
  env:
    ZK_HEAP_SIZE: "1G"
  persistence:
    enabled: false
  image:
    PullPolicy: "IfNotPresent"
  url: ""
  port: 2181
